# Generated by Django 3.2 on 2024-11-26 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='titlegenre',
            table='reviews_titlegenre',
        ),
    ]
