# Generated by Django 3.2 on 2024-11-26 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_rename_title_id_review_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='review_id',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='title_id',
            new_name='title',
        ),
    ]
